### ISSUE TITLE
release on supermarket

### ISSUE THREAD

**Issue by rmoriz** [TelekomLabs/chef-ssh-hardening#62]
Hi,

just discovered the #24 bug when using this cookbook. Looks like there was no release of this cookbook on chef supermarket since June, 24th - any plans to cut a new release?

best

**Comment by arlimus** [comment]
Sorry for the delay, Christmas and New Years has a harsh effect on productivity ;)
We are wrapping up a couple of issues ( #64 - #66 ) and will have the release ready. If the issues take longer to resolve, I'll push the update at latest on Monday. 
Thanks for posting!

**Comment by arlimus** [comment]
We'll improve version updates in the future. Sorry it took so long.
