### ISSUE TITLE
Suggestion: Don't populate /root/.ssh/authorized_keys by default

### ISSUE THREAD

**Issue by mkonecny** [TelekomLabs/chef-ssh-hardening#69]
When `@node['ssh']['allow_root_with_key'] == false` (default) we set `PermitRootLogin no` in opensshd.conf.

In this case, we should not touch `/root/.ssh/authorized_keys` as well.

**Comment by mkonecny** [comment]
I see that working with remote "authorized_keys" is now deprecated, and so this issue is irrelevant. Closing.

**Comment by chris-rock** [comment]
@mkonecny Thanky you very much anyway. In case you find anything, please report it. This will enable us to improve the cookbooks to the specific needs
