### ISSUE TITLE
Allow management of allow/deny users

### ISSUE THREAD

**Issue by Rockstar04** [TelekomLabs/chef-ssh-hardening#75]
The sshd template has a commented out section to explicitly allow and deny groups and I would love to be able to manage these with chef.

https://github.com/TelekomLabs/chef-ssh-hardening/blob/master/templates/default/opensshd.conf.erb#L121-L125

Would this be within the scope of this cookbook or should I override the template in a wrapper cookbook? This seems like it would be fairly simple to implement and I would gladly open a PR with the changes.

**Comment by chris-rock** [comment]
@Rockstar04 great idea and a pull request is welcome

**Comment by Rockstar04** [comment]
Closed in favor of pull request #76
